### ISSUE TITLE
Wrong timestamp conversion in case of TimeTenMics time resolution is used in BLF file.

### ISSUE THREAD

**Issue by karolbrk** [Technica-Engineering/Technica.Traces.Blf.Converter#17]
After converting BLF ethernet log with timestamp resolution TimeTenMics the timestamp in output PCAPNG is wrong - divided by 1000 compered to original value. 

Timestamp in input BLF file:
 ![BLF_timestamp](https://github.com/Technica-Engineering/Technica.Traces.Blf.Converter/assets/25886197/c772cc8e-9852-42ca-9958-36993ab473b8)

Timestamp in output PCAPNG file:
![PCAPNG_timestamp](https://github.com/Technica-Engineering/Technica.Traces.Blf.Converter/assets/25886197/7d98bb57-afbb-480c-b05b-a50d4f404b25)

**Comment by kayoub5** [comment]
@karolbrk got a sample file?

**Comment by karolbrk** [comment]
Thanks for quick fix!
